### PR TITLE
fix SAMD51 spurious writes; allow gcc9 compilation; improve delay() calibration

### LINKED ISSUE #86: update-bootloader*.ino Arduino sketch make a brick
Hello everyone, I have been playing with Microsoft's UF2 file system for microcontrollers, I have followed the examples and the Board version MKR1010 has been successfully compiled, in addition to the firmware file * .bin a sketch is generated for the Arduino IDE , but when you upload it to the Board, something breaks and turns it into a brick, so to recover it, I must use OpenOCD in conjunction with a Raspberry, my question is if any of you have tried and solved this problem, I have also made for the SparkFun SAMD21 Dev Breakout Board

### LINKED ISSUE #95: Feather M4 express: bytes above BOOTPROT being zeroed
Complete details provided in this post:
https://forums.adafruit.com/viewtopic.php?f=57&t=158718

Feather M4 Express does not launch user code because memory locations at the beginning of unprotected FLASH memory are being cleared (set to 0x0) during power-on.

Arduino IDE v1.8.10
Adafruit Feather M4 Express; part #3857
Adafruit FeatherWing OLED 128x32; part #2900
Adafruit bootloader v3.7.0
Adafruit_SSD1306 library v2.0.2

No additional hardware is required. Just stack a Feather and OLED, install 'my version 3' then cycle power on/off. The failure usually occurs within 100 on/off power cycles but it is random and may require thousands of power-on-cycles to observe the failure. I automated cycling power at 500ms ON, 500ms OFF.

'my version 3' application code provided below

[EDIT: turned into an attachment for easier downloading -- @dhalbert]

[v3.ino.txt](https://github.com/adafruit/uf2-samdx1/files/3995329/v3.ino.txt)

### LINKED ISSUE #99: Feather M0 gets bricked
Hello, I followed this tutorial (https://learn.adafruit.com/installing-circuitpython-on-samd21-boards/installing-the-uf2-bootloader) on 3 M0 Feather boards and it bricked them all. I followed the directions perfectly every time and I used the Arduino INO file that is posed in this repository. I think there is an issue with the INO file. Also, in case it helps, the boards I used most recently were the Adalogger M0. Thanks for looking into this.

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #95.
Fixes #86.
Fixes #99.

- When starting the bootloader, for SAMD51, busy-wait until detected voltage is at least 2.7V, then wait 100msecs for the voltage to stabilize, then set auto-reset if voltage goes below 2.7V. Busy-waiting prevents multiple resets while the voltage is rising or glitching. As noted in #95, I tested the spurious writes fix for a number of hours.
Note that we can't enable `BOD33` in the user page fuses, because of an erratum that doing that can prevent attaching a debugging probe.
- Set auto wait states for SAMD51 NVM.
- Improve calibration of `delay()` routine, handle different cpu frequencies, and handle LED pulse interrupts, which affect calibration.
- Remove `sp` "register clobber" designation, which gcc9 doesn't like.
- Fix `update-bootloader...info` sketches. Rewrite of `sketch.cpp`: clean up, make safer, verify write.
- Suppress generating `.ino` updaters for SAMD51 boards; they don't work.

### CODE REVIEW

**Comment by dhalbert** [comment]
@tannewt hold off on this; still debugging some M0 stuff

**Comment by ladyada** [comment]
i knew you would figure it out :D dandan noodle delivery!

File: src/init_samd21.c [hunk 1]
```diff
@@ -7,6 +7,9 @@
 
 volatile bool g_interrupt_enabled = true;
 
+// SAMD51 starts at 1MHz by default.
```
Comment (tannewt) [inline src/init_samd21.c]:
```suggestion
// SAMD21 starts at 1MHz by default.
```

File: src/init_samd51.c [hunk 2]
```diff
@@ -79,6 +82,7 @@ void system_init(void) {
     MCLK->CPUDIV.reg = MCLK_CPUDIV_DIV_DIV1;
 
     SysTick_Config(1000);
+    current_cpu_frequency_MHz = 48;
```
Comment (tannewt) [inline src/init_samd51.c]: Why reset this?

File: src/main.c [hunk 3]
```diff
@@ -68,7 +68,7 @@
  *
  * Applications compiled to be executed along with the bootloader will start at
  * 0x2000 (samd21) or 0x4000 (samd51)
- * The bootloader doesn't changes the VTOR register, application code is 
+ * The bootloader doesn't changes the VTOR register, application code is
```
Comment (tannewt) [inline src/main.c]: This is a lie: https://github.com/adafruit/uf2-samdx1/blob/master/src/main.c#L143

UF2 does set VTOR.

File: src/main.c [hunk 4]
```diff
@@ -166,8 +166,31 @@ int main(void) {
...
+    // Also without this higher level, the SAMD51 will write zeros to flash intermittently.
+    // Disable while changing level.
+    SUPC->BOD33.bit.ENABLE = 0;
+    SUPC->BOD33.bit.LEVEL = 200;  // 2.7V: 1.5V + LEVEL * 6mV.
+    // Don't reset right now.
+    SUPC->BOD33.bit.ACTION = SUPC_BOD33_ACTION_NONE_Val;
+    SUPC->BOD33.bit.ENABLE = 1; // enable brown-out detection
+
+    while (SUPC->STATUS.bit.BOD33DET) {
+        // Wait for voltage to rise above BOD33 value.
```
Comment (tannewt) [inline src/main.c]: This will busy wait the CPU. Do you want to use the BOD33 to do the wake up? You could set the action to interrupt and then WFI. That way you won't burn as much power while a battery charges. (You could also use WAKEEN and the lower power modes too.)

File: src/main.c [hunk 5]
```diff
@@ -166,8 +166,31 @@ int main(void) {
...
+    }
+    // Wait 100ms for voltage to stabilize.
+    delay(100);
+
```
Comment (tannewt) [inline src/main.c]: Want to do one more final check of the detector here to make sure the voltage is ok?

File: src/main.c (hunk 4 above)
Comment (dhalbert) [reply src/main.c:182]: That's a good possibility. I have to configure the BOD33 to be active in a certain sleep mode. Based on your newfound knowledge of sleeping, do you have a suggestion of whether to set `SLEEPCFG.SLEEPMODE` to `IDLE` or to `STANDBY`?

I don't even need a real interrupt handler because I can just check the BOD33 status after the WFI completes, and repeat if it's still too low.

File: src/main.c (hunk 5 above)
Comment (dhalbert) [reply src/main.c:186]: I was thinking of that; I'd repeat until it was stable. Also, I should do this only on certain reset causes, not always. Right now this small delay makes double click tricker (you have to do it slightly slower than you used to).

File: src/main.c (hunk 4 above)
Comment (dhalbert) [reply src/main.c:182]: Hmm, it turns out there is no interrupt that fires when the voltage has _risen_ to the specified level; the interrupt available is only when it falls below the level.

File: src/main.c (hunk 5 above)
Comment (dhalbert) [reply src/main.c:193]: done

File: src/main.c (hunk 4 above)
Comment (dhalbert) [reply src/main.c:180]: An alternative would be to sleep for a short while and re-check, but that requires enabling the low-power clocks, etc. I'd like to defer doing that until later, so that we have a solid bootloader that fixes the fundamental problem. Later we can add better low-power handling. The current busy-wait is no worse than the repeated reset that would happen at the edge of the BOD33 value.

I'm running a multi-hour test right now; it's doing fine.

Comment (tannewt) [reply src/main.c:180]: Probably not worth the complexity at this point. Two options would be:

1) Use the RTC or a timer to sleep a fixed duration between checks.
2) Use an analog comparator to monitor the voltage and wake us up.

It doesn't look like we can use the SUPC to wake us up because the VBAT isn't connected and therefore we can't switch to and from it.

File: src/main.c (hunk 5 above)
Comment (tannewt) [reply src/main.c:193]: Ya, checking reset cause would be good. We're going to need something similar in CircuitPython once we reset on events.

Comment (dhalbert) [reply src/main.c:193]: new commit  now checks reset cause

File: src/main.c [hunk 6]
```diff
@@ -166,6 +164,37 @@ int main(void) {
...
+    // which is too low for proper operation of external SPI flash chips (they are 2.7-3.6V).
+    // Also without this higher level, the SAMD51 will write zeros to flash intermittently.
+    // Disable while changing level.
+    SUPC->BOD33.bit.ENABLE = 0;
+    SUPC->BOD33.bit.LEVEL = 200;  // 2.7V: 1.5V + LEVEL * 6mV.
+    // Don't reset right now.
+    SUPC->BOD33.bit.ACTION = SUPC_BOD33_ACTION_NONE_Val;
+    SUPC->BOD33.bit.ENABLE = 1; // enable brown-out detection
+
+    while (SUPC->STATUS.bit.BOD33DET) {
```
Comment (tannewt) [inline src/main.c:179]: Is it worth checking BOD33RDY too? That way you ensure it's actually active.

File: src/main.c [hunk 7]
```diff
@@ -166,6 +164,37 @@ int main(void) {
 #elif defined(SAMD51)
     WDT->CTRLA.reg = 0;
     while(WDT->SYNCBUSY.reg) {}
+
+    // Enable 2.7V brownout detection. The default fuse value is 1.7
+    // Set brownout detection to ~2.7V. Default from factory is 1.7V,
+    // which is too low for proper operation of external SPI flash chips (they are 2.7-3.6V).
+    // Also without this higher level, the SAMD51 will write zeros to flash intermittently.
+    // Disable while changing level.
+    SUPC->BOD33.bit.ENABLE = 0;
```
Comment (tannewt) [inline src/main.c:173]: I think you may need to busy spin on B33SRDY after changing ENABLE. The BOD33 register is documented as write-synchronized.

**Comment by dhalbert** [comment]
Latest version ran overnight with test program without any spurious writes.
